engines:
  pmd:
    enabled: true
    channel: "beta"
  checkstyle:
    enabled: true
    channel: "beta"
    configLocation: "checkstyle.xml"
    consoleOutput: true
    checks:
      com.puppycrawl.tools.checkstyle.checks.javadoc.JavadocMethodCheck:
        enabled: false

ratings:
  paths:
  - "**.java"