env:
  global:
    - CC_TEST_REPORTER_ID=4aea7d19ff53f24642fbe6c1ec89555a7bc15c806c6f5f58734d0b7c3d177344
    - GIT_COMMITTED_AT=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then git log -1 --pretty=format:%ct; else git log -1 --skip 1 --pretty=format:%ct; fi)
language: java
jdk:
  - openjdk8
before_script:
  - cd src/main/java
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then ./cc-test-reporter before-build; fi
  - cd ../../..
after_success:
  - mvn -B cobertura:cobertura coveralls:report
  - cp target/site/cobertura/coverage.xml src/main/java/cobertura.xml #copy cobertura file so codeclimate can find it
  - cd src/main/java
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then ./cc-test-reporter after-build -t cobertura --exit-code $TRAVIS_TEST_RESULT; fi
